# Generated by Django 2.1.7 on 2019-02-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='coupons',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
